version: '3.8'

services:
    frontend:
        build: .
        container_name: next15-shadcn
        ports:
            - '80:3000' # Change to your frontend app's port if different
        restart: always
        networks:
            - frontend-network

networks:
    frontend-network:
        driver: bridge
